// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load environment variables from .env.local first (higher priority), then .env
// This matches Next.js behavior where .env.local takes precedence
config({ path: ".env.local" }); // Load .env.local first
config(); // Then load .env (will not override existing vars from .env.local)

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
